### PR TITLE
Script to generate unistd.d files and initial output

### PR DESCRIPTION
**Pull request by n8sh**
https://github.com/libmir/mir-random/pull/51#issuecomment-341021878

I split the files based on the D version names rather than their names in the Linux source code.

Because names beginning with "__" are reserved in D, I used a prefix of `NR_` instead of `__NR_`.

Right now the files are written assuming they will only be imported on the architecture they are for. For instance, `mir.linux.arch.sparc.uapi.asm.unistd` and `mir.linux.arch.sparc64.uapi.asm.unistd` are identical: they check `size_t.sizeof` to determine whether to define constants for 32-bit or 64-bit SPARC.

### CODE REVIEW

**Review by 9il — APPROVED** [review]
Wow, awesome!

**Comment by 9il** [comment]
The PR is approved, feel free to merge and announce it when ready

**Comment by n8sh** [comment]
@9il Okay now it's ready to use https://github.com/libmir/mir-linux-kernel/commit/bd5dfa6bb4edefb0d750e2a0cd84e709ed5185e7 
I can make a forum announcement but I think it would be best if you were the one who registered it with DUB so the "registered by" will match the other Mir packages.

**Comment by 9il** [comment]
http://code.dlang.org/packages/mir-linux-kernel

**Pull request merged**
