### PR TITLE
Allow library and shared library generation

### PR DESCRIPTION
**Pull request by bioinfornatics**
This allow to create `.so` and `.a` library file

### CODE REVIEW

**Comment by 9il** [comment]
Why the files are required? It is a header only library that contains definitions and constants.

**Comment by bioinfornatics** [comment]
Indeed I was trying to build mir-random from source without its bundle dependencies and got failure due to the missing code mir-linux-kernel. So to solve this (too quickly) I created the `.so` file and resolve the build failure. But now I see that was not the good idea.

Little question why this code is not directly into mir-random with the conditional compilation statement `version(linux){ ... }`

**Comment by 9il** [comment]
The package is also used by other DUB packages, at least by `vibe-d:crypto`.
Automatically generated D Linux headers are much more useful and stable comparing with manual syscall versioning for all targets.

**Comment by 9il** [comment]
BTW, meson should download the dependency code when required to build a package.

**Pull request closed without merging**
